apiVersion: apps/v1
kind: Deployment
metadata:
  name: did-service
  labels:
    arch: inner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: did-service
  template:
    metadata:
      labels:
        app: did-service
    spec:
      nodeSelector:
        app: keywe-service
      containers:
        - name: did-service
          image: sunwoo11/keywe_did_service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 60005
            - containerPort: 50005
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: config-server-url
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: rabbitmq-host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: rabbitmq-port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: rabbitmq-username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: rabbitmq-password
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: eureka-host
            - name: EUREKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: eureka-port
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: db-host
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: db-port
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: db-pass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: did-db-name
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: did-service-port
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: did-grpc-port
          resources:
            requests:
              memory: "512Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "1"
                  
---

apiVersion: v1
kind: Service
metadata:
  name: did-service
  labels:
    arch: inner
spec:
  selector:
    app: did-service
  ports:
    - port: 60005
      targetPort: 60005
      name: http
    - port: 50005
      targetPort: 50005
      name: grpc