apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  labels:
    arch: outer
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/sunwoo11/keywe_service_discovery:latest
    argocd-image-updater.argoproj.io/update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: develop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      nodeSelector:
        app: keywe-service
      initContainers:
        - name: wait-for-config-server
          image: curlimages/curl:8.5.0
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for config-server to be healthy..."
              until curl -sf http://config-server:8888/actuator/health | grep '"status":"UP"'; do
                echo "⏱️ config-server not ready yet..."
                sleep 5
              done
              echo "✅ config-server is healthy. Continuing..."
      containers:
        - name: service-discovery
          image: sunwoo11/keywe_service_discovery:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: config-server-url
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: rabbitmq-host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: rabbitmq-port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: rabbitmq-username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: rabbitmq-password
