nodeSelector:
  role: monitoring
  app: infra
tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1
    memory: 2Gi

meshConfig:
  enablePrometheusMerge: true

