apiVersion: apps/v1
kind: Deployment
metadata:
  name: member-service
  labels:
    arch: inner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: member-service
  template:
    metadata:
      labels:
        app: member-service
        sidecar.istio.io/inject: "true"
    spec:
      nodeSelector:
        app: keywe-service
      containers:
        - name: member-service
          image: sunwoo11/keywe_member_service:dev
          imagePullPolicy: Always
          ports:
            - containerPort: 60001
            - containerPort: 60001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_PROFILES_INCLUDE
              value: "actuator,swagger,redis,k8s-grpc,datasource"
            - name: CONFIG_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: config-server-url
            - name: SPRING_RABBITMQ_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: rabbitmq-host
            - name: SPRING_RABBITMQ_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: rabbitmq-port
            - name: SPRING_RABBITMQ_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: rabbitmq-username
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: rabbitmq-password
            - name: EUREKA_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: eureka-host
            - name: EUREKA_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: eureka-port
            - name: MYSQL_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: db-host
            - name: MYSQL_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: db-port
            - name: MYSQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: db-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: db-pass
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: mem-db-name
            - name: JWT_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: jwt-access-token-secret
            - name: JWT_REFRESH_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: keywe-secrets
                  key: jwt-refresh-token-secret
            - name: JWT_ACCESS_TOKEN_EXPIRATION_TIME
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: jwt-access-token-expiration-time
            - name: JWT_REFRESH_TOKEN_EXPIRATION_TIME
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: jwt-refresh-token-expiration-time
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: mobile-redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: mobile-redis-port
            - name: REDIS_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: mobile-redis-password
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: member-service-port
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  name: keywe-config
                  key: member-grpc-port
          resources:
            requests:
              memory: "512Mi"
              cpu: "150m"
            limits:
              memory: "1Gi"
              cpu: "1"
---

apiVersion: v1
kind: Service
metadata:
  name: member-service
  labels:
    arch: inner
spec:
  selector:
    app: member-service
  ports:
    - port: 60001
      targetPort: 60001
      name: http
    - port: 50001
      targetPort: 50001
      name: grpc
